language: cpp
compiler: 
- gcc
script: 
- if [ $TRAVIS_OS_NAME == linux ]; then ./build_parsnp_linux.sh; fi 
notifications:
  email:
    recipients:
      - treangent@nbacc.net
    on_success: change
    on_failure: change
os:
- linux
